/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as WelcomeRouteRouteImport } from './routes/welcome/route'
import { Route as URouteRouteImport } from './routes/u/route'
import { Route as TermsRouteRouteImport } from './routes/terms/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ResetPasswordRouteRouteImport } from './routes/reset-password/route'
import { Route as PrivacyRouteRouteImport } from './routes/privacy/route'
import { Route as PRouteRouteImport } from './routes/p/route'
import { Route as NewRouteRouteImport } from './routes/new/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as PPostIdRouteImport } from './routes/p/$postId'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as DemoUpcomingRouteImport } from './routes/demo/upcoming'
import { Route as DemoTransactionsRouteImport } from './routes/demo/transactions'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoGoalsRouteImport } from './routes/demo/goals'
import { Route as DemoBudgetsRouteImport } from './routes/demo/budgets'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoAccountsRouteImport } from './routes/demo/accounts'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppRecurringRouteImport } from './routes/app/recurring'
import { Route as AppMoneyPlanRouteImport } from './routes/app/money-plan'
import { Route as AppInsightsRouteImport } from './routes/app/insights'
import { Route as AppHouseholdRouteImport } from './routes/app/household'
import { Route as AppGoalsRouteImport } from './routes/app/goals'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppBudgetsRouteImport } from './routes/app/budgets'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppAccountsRouteImport } from './routes/app/accounts'
import { Route as AppReportsHouseholdRouteImport } from './routes/app/reports/household'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PPostIdEditRouteRouteImport } from './routes/p/$postId/edit/route'
import { Route as PPostIdEditIndexRouteImport } from './routes/p/$postId/edit/index'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRouteRoute = WelcomeRouteRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const URouteRoute = URouteRouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRouteRoute = TermsRouteRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRouteRoute = ResetPasswordRouteRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRouteRoute = PrivacyRouteRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PRouteRoute = PRouteRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRouteRoute = NewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WelcomeRouteRoute,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TermsRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivacyRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => URouteRoute,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUpcomingRoute = DemoUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTransactionsRoute = DemoTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/prisma',
  path: '/prisma',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoGoalsRoute = DemoGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoBudgetsRoute = DemoBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/better-auth',
  path: '/better-auth',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoAccountsRoute = DemoAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DemoRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMoneyPlanRoute = AppMoneyPlanRouteImport.update({
  id: '/money-plan',
  path: '/money-plan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHouseholdRoute = AppHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsHouseholdRoute = AppReportsHouseholdRouteImport.update({
  id: '/reports/household',
  path: '/reports/household',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PPostIdEditRouteRoute = PPostIdEditRouteRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PPostIdRoute,
} as any)
const PPostIdEditIndexRoute = PPostIdEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PPostIdEditRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/new': typeof NewRouteRoute
  '/p': typeof PRouteRouteWithChildren
  '/privacy': typeof PrivacyRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/terms': typeof TermsRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/welcome': typeof WelcomeRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/household': typeof AppHouseholdRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/money-plan': typeof AppMoneyPlanRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/budgets': typeof DemoBudgetsRoute
  '/demo/goals': typeof DemoGoalsRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/transactions': typeof DemoTransactionsRoute
  '/demo/upcoming': typeof DemoUpcomingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$postId': typeof PPostIdRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/login/': typeof LoginIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/p/$postId/edit': typeof PPostIdEditRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/reports/household': typeof AppReportsHouseholdRoute
  '/p/$postId/edit/': typeof PPostIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRouteRoute
  '/p': typeof PRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/household': typeof AppHouseholdRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/money-plan': typeof AppMoneyPlanRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/budgets': typeof DemoBudgetsRoute
  '/demo/goals': typeof DemoGoalsRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/transactions': typeof DemoTransactionsRoute
  '/demo/upcoming': typeof DemoUpcomingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$postId': typeof PPostIdRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/about': typeof AboutIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/demo': typeof DemoIndexRoute
  '/login': typeof LoginIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/terms': typeof TermsIndexRoute
  '/welcome': typeof WelcomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/reports/household': typeof AppReportsHouseholdRoute
  '/p/$postId/edit': typeof PPostIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/new': typeof NewRouteRoute
  '/p': typeof PRouteRouteWithChildren
  '/privacy': typeof PrivacyRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/terms': typeof TermsRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/welcome': typeof WelcomeRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/household': typeof AppHouseholdRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/money-plan': typeof AppMoneyPlanRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/budgets': typeof DemoBudgetsRoute
  '/demo/goals': typeof DemoGoalsRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/transactions': typeof DemoTransactionsRoute
  '/demo/upcoming': typeof DemoUpcomingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$postId': typeof PPostIdRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/login/': typeof LoginIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/p/$postId/edit': typeof PPostIdEditRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/reports/household': typeof AppReportsHouseholdRoute
  '/p/$postId/edit/': typeof PPostIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/demo'
    | '/login'
    | '/new'
    | '/p'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/u'
    | '/welcome'
    | '/explore'
    | '/legal-notice'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/start'
    | '/app/accounts'
    | '/app/billing'
    | '/app/budgets'
    | '/app/explore'
    | '/app/goals'
    | '/app/household'
    | '/app/insights'
    | '/app/money-plan'
    | '/app/recurring'
    | '/app/transactions'
    | '/billing/success'
    | '/blog/$slug'
    | '/demo/accounts'
    | '/demo/better-auth'
    | '/demo/budgets'
    | '/demo/goals'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/demo/transactions'
    | '/demo/upcoming'
    | '/invite/$token'
    | '/p/$postId'
    | '/u/$username'
    | '/about/'
    | '/app/'
    | '/blog/'
    | '/demo/'
    | '/login/'
    | '/privacy/'
    | '/reset-password/'
    | '/settings/'
    | '/terms/'
    | '/welcome/'
    | '/p/$postId/edit'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/reports/household'
    | '/p/$postId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/p'
    | '/u'
    | '/explore'
    | '/legal-notice'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/start'
    | '/app/accounts'
    | '/app/billing'
    | '/app/budgets'
    | '/app/explore'
    | '/app/goals'
    | '/app/household'
    | '/app/insights'
    | '/app/money-plan'
    | '/app/recurring'
    | '/app/transactions'
    | '/billing/success'
    | '/blog/$slug'
    | '/demo/accounts'
    | '/demo/better-auth'
    | '/demo/budgets'
    | '/demo/goals'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/demo/transactions'
    | '/demo/upcoming'
    | '/invite/$token'
    | '/p/$postId'
    | '/u/$username'
    | '/about'
    | '/app'
    | '/blog'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/welcome'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/reports/household'
    | '/p/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/demo'
    | '/login'
    | '/new'
    | '/p'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/u'
    | '/welcome'
    | '/explore'
    | '/legal-notice'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/start'
    | '/app/accounts'
    | '/app/billing'
    | '/app/budgets'
    | '/app/explore'
    | '/app/goals'
    | '/app/household'
    | '/app/insights'
    | '/app/money-plan'
    | '/app/recurring'
    | '/app/transactions'
    | '/billing/success'
    | '/blog/$slug'
    | '/demo/accounts'
    | '/demo/better-auth'
    | '/demo/budgets'
    | '/demo/goals'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/demo/transactions'
    | '/demo/upcoming'
    | '/invite/$token'
    | '/p/$postId'
    | '/u/$username'
    | '/about/'
    | '/app/'
    | '/blog/'
    | '/demo/'
    | '/login/'
    | '/privacy/'
    | '/reset-password/'
    | '/settings/'
    | '/terms/'
    | '/welcome/'
    | '/p/$postId/edit'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/app/reports/household'
    | '/p/$postId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  NewRouteRoute: typeof NewRouteRoute
  PRouteRoute: typeof PRouteRouteWithChildren
  PrivacyRouteRoute: typeof PrivacyRouteRouteWithChildren
  ResetPasswordRouteRoute: typeof ResetPasswordRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  TermsRouteRoute: typeof TermsRouteRouteWithChildren
  URouteRoute: typeof URouteRouteWithChildren
  WelcomeRouteRoute: typeof WelcomeRouteRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  BlogSlugRoute: typeof BlogSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/'
      fullPath: '/welcome/'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof WelcomeRouteRoute
    }
    '/terms/': {
      id: '/terms/'
      path: '/'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof TermsRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof PrivacyRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof URouteRoute
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/upcoming': {
      id: '/demo/upcoming'
      path: '/upcoming'
      fullPath: '/demo/upcoming'
      preLoaderRoute: typeof DemoUpcomingRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/transactions': {
      id: '/demo/transactions'
      path: '/transactions'
      fullPath: '/demo/transactions'
      preLoaderRoute: typeof DemoTransactionsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/goals': {
      id: '/demo/goals'
      path: '/goals'
      fullPath: '/demo/goals'
      preLoaderRoute: typeof DemoGoalsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/budgets': {
      id: '/demo/budgets'
      path: '/budgets'
      fullPath: '/demo/budgets'
      preLoaderRoute: typeof DemoBudgetsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/accounts': {
      id: '/demo/accounts'
      path: '/accounts'
      fullPath: '/demo/accounts'
      preLoaderRoute: typeof DemoAccountsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/recurring': {
      id: '/app/recurring'
      path: '/recurring'
      fullPath: '/app/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/money-plan': {
      id: '/app/money-plan'
      path: '/money-plan'
      fullPath: '/app/money-plan'
      preLoaderRoute: typeof AppMoneyPlanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/household': {
      id: '/app/household'
      path: '/household'
      fullPath: '/app/household'
      preLoaderRoute: typeof AppHouseholdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/budgets': {
      id: '/app/budgets'
      path: '/budgets'
      fullPath: '/app/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports/household': {
      id: '/app/reports/household'
      path: '/reports/household'
      fullPath: '/app/reports/household'
      preLoaderRoute: typeof AppReportsHouseholdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$postId/edit': {
      id: '/p/$postId/edit'
      path: '/edit'
      fullPath: '/p/$postId/edit'
      preLoaderRoute: typeof PPostIdEditRouteRouteImport
      parentRoute: typeof PPostIdRoute
    }
    '/p/$postId/edit/': {
      id: '/p/$postId/edit/'
      path: '/'
      fullPath: '/p/$postId/edit/'
      preLoaderRoute: typeof PPostIdEditIndexRouteImport
      parentRoute: typeof PPostIdEditRouteRoute
    }
  }
}

interface AboutRouteRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppExploreRoute: typeof AppExploreRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppHouseholdRoute: typeof AppHouseholdRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMoneyPlanRoute: typeof AppMoneyPlanRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReportsHouseholdRoute: typeof AppReportsHouseholdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppExploreRoute: AppExploreRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppHouseholdRoute: AppHouseholdRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMoneyPlanRoute: AppMoneyPlanRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppReportsHouseholdRoute: AppReportsHouseholdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DemoRouteRouteChildren {
  DemoAccountsRoute: typeof DemoAccountsRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoBudgetsRoute: typeof DemoBudgetsRoute
  DemoGoalsRoute: typeof DemoGoalsRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTransactionsRoute: typeof DemoTransactionsRoute
  DemoUpcomingRoute: typeof DemoUpcomingRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoAccountsRoute: DemoAccountsRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoBudgetsRoute: DemoBudgetsRoute,
  DemoGoalsRoute: DemoGoalsRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTransactionsRoute: DemoTransactionsRoute,
  DemoUpcomingRoute: DemoUpcomingRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface PPostIdEditRouteRouteChildren {
  PPostIdEditIndexRoute: typeof PPostIdEditIndexRoute
}

const PPostIdEditRouteRouteChildren: PPostIdEditRouteRouteChildren = {
  PPostIdEditIndexRoute: PPostIdEditIndexRoute,
}

const PPostIdEditRouteRouteWithChildren =
  PPostIdEditRouteRoute._addFileChildren(PPostIdEditRouteRouteChildren)

interface PPostIdRouteChildren {
  PPostIdEditRouteRoute: typeof PPostIdEditRouteRouteWithChildren
}

const PPostIdRouteChildren: PPostIdRouteChildren = {
  PPostIdEditRouteRoute: PPostIdEditRouteRouteWithChildren,
}

const PPostIdRouteWithChildren =
  PPostIdRoute._addFileChildren(PPostIdRouteChildren)

interface PRouteRouteChildren {
  PPostIdRoute: typeof PPostIdRouteWithChildren
}

const PRouteRouteChildren: PRouteRouteChildren = {
  PPostIdRoute: PPostIdRouteWithChildren,
}

const PRouteRouteWithChildren =
  PRouteRoute._addFileChildren(PRouteRouteChildren)

interface PrivacyRouteRouteChildren {
  PrivacyIndexRoute: typeof PrivacyIndexRoute
}

const PrivacyRouteRouteChildren: PrivacyRouteRouteChildren = {
  PrivacyIndexRoute: PrivacyIndexRoute,
}

const PrivacyRouteRouteWithChildren = PrivacyRouteRoute._addFileChildren(
  PrivacyRouteRouteChildren,
)

interface ResetPasswordRouteRouteChildren {
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
}

const ResetPasswordRouteRouteChildren: ResetPasswordRouteRouteChildren = {
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
}

const ResetPasswordRouteRouteWithChildren =
  ResetPasswordRouteRoute._addFileChildren(ResetPasswordRouteRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface TermsRouteRouteChildren {
  TermsIndexRoute: typeof TermsIndexRoute
}

const TermsRouteRouteChildren: TermsRouteRouteChildren = {
  TermsIndexRoute: TermsIndexRoute,
}

const TermsRouteRouteWithChildren = TermsRouteRoute._addFileChildren(
  TermsRouteRouteChildren,
)

interface URouteRouteChildren {
  UUsernameRoute: typeof UUsernameRoute
}

const URouteRouteChildren: URouteRouteChildren = {
  UUsernameRoute: UUsernameRoute,
}

const URouteRouteWithChildren =
  URouteRoute._addFileChildren(URouteRouteChildren)

interface WelcomeRouteRouteChildren {
  WelcomeIndexRoute: typeof WelcomeIndexRoute
}

const WelcomeRouteRouteChildren: WelcomeRouteRouteChildren = {
  WelcomeIndexRoute: WelcomeIndexRoute,
}

const WelcomeRouteRouteWithChildren = WelcomeRouteRoute._addFileChildren(
  WelcomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  NewRouteRoute: NewRouteRoute,
  PRouteRoute: PRouteRouteWithChildren,
  PrivacyRouteRoute: PrivacyRouteRouteWithChildren,
  ResetPasswordRouteRoute: ResetPasswordRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  TermsRouteRoute: TermsRouteRouteWithChildren,
  URouteRoute: URouteRouteWithChildren,
  WelcomeRouteRoute: WelcomeRouteRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  BlogSlugRoute: BlogSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
